Talend/data-quality

pom.xml

As it maven tools can detect license.

Add license information in pom

---

dataquality-semantic/src/main/java/org/talend/dataquality/semantic/broadcast/BroadcastDocumentObject.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/broadcast/BroadcastIndexObject.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/broadcast/BroadcastIndexObjectTest.java

* Change access level for BroadcastDocumentObject for use in other products.
* Adds ability to create a BroadcastIndexObject based on BroadcastDocumentObject iso. Lucene directory.

feat(TDP-2757): Changes for Streams integration

---

dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/swoosh/RichRecord.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/record/linkage/AllRecordLinkageTests.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/record/linkage/grouping/swoosh/RichRecordTest.java

fixed dailog can not be open issue when mutilpass

bug fixed TDQ-13053 SurvivorShip rules impact the grouping of swoosh and

---

dataquality-common/README.md
dataquality-converters/README.md
dataquality-email/README.md
dataquality-libraries/pom.xml
dataquality-record-linkage/README.md
dataquality-sampling/README.md
dataquality-semantic-model/README.md
dataquality-semantic/README.md
dataquality-standardization/README.md
dataquality-statistics/README.md
dataquality-wordnet/README.md
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [master]

---

dataquality-common/README.md
dataquality-libraries/pom.xml
dataquality-record-linkage/README.md
dataquality-sampling/README.md
dataquality-semantic/README.md
dataquality-standardization/README.md
dataquality-statistics/README.md
dataquality-wordnet/README.md
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/1.4]

---

dataquality-common/README.md
dataquality-email/README.md
dataquality-libraries/pom.xml
dataquality-record-linkage/README.md
dataquality-sampling/README.md
dataquality-semantic-model/README.md
dataquality-semantic/README.md
dataquality-standardization/README.md
dataquality-statistics/README.md
dataquality-wordnet/README.md
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/1.5]

---

dataquality-converters/src/main/java/org/talend/dataquality/converters/DistanceConverter.java
dataquality-converters/src/test/java/org/talend/dataquality/converters/DistanceConverterTest.java

TDQ-13221 Optimized code
TDQ-13221 resolve code quality issue

TDQ-13221 Create API that converts distances

---

dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/AbstractRecordGrouping.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/TSwooshGrouping.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/swoosh/ComponentSwooshMatchRecordGrouping.java

Hi Sebastiao,
please review this solution. if it is ok, please merge it to master.
Thanks!

TDQ-13225 TDQ-13372 output the non-master data of 1st tMatchGroup.

---

dataquality-converters/src/main/java/org/talend/dataquality/converters/StringConverter.java
dataquality-converters/src/test/java/org/talend/dataquality/converters/StringConverterTest.java

TDQ-13269: fix when select whitespace will handle all the list values at

---

dataquality-statistics/src/main/java/org/talend/dataquality/statistics/cardinality/AbstractCardinalityStatistics.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/cardinality/CardinalityHLLStatistics.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/cardinality/CardinalityStatistics.java

Addition of getters and setter for : 
- Count attribute in AbstractCardinalityStatistics
- DistinctData attribute in CardinalityStatistics (the setter is pseudo setter using "addAll" method because the attribute is final).
Also some minor corrections in the JavaDoc for the merge methods

Addition of getter&setters

---

dataquality-statistics/src/main/java/org/talend/dataquality/statistics/cardinality/CardinalityHLLStatistics.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/frequency/recognition/TypoUnicodePatternRecognizer.java
dataquality-statistics/src/test/java/org/talend/dataquality/statistics/frequency/recognition/TypoUnicodePatternRecognizerTest.java

Addition of a new Pattern Recognizer which instead of recognizing [aaaAAaa999] recognize :
- [char]
- [word]
- [digit]
- [number]
- [ideogram]
etc. (see the documentation of the code)

Tdq 13389 new pattern recognition

---

dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/TSwooshGrouping.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/record/linkage/grouping/TSwooshGroupingTest.java

TDQ-13490 avoid to output duplicate none-master records when swoosh with

---

dataquality-statistics/src/main/java/org/talend/dataquality/statistics/frequency/recognition/TypoUnicodePatternRecognizer.java

Delete "type" attribute and do a switch on the class itself with a switch(this) and some other minor improvements

Minor changes to the New Pattern Recognizer class for optimization

---

dataquality-semantic/src/main/java/org/talend/dataquality/semantic/statistics/SemanticQualityAnalyzer.java

- by calculating the category ID list from category name in advance

TDQ-13676 Name to ID category performance impact

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-libraries/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

(following the creation of maintenance/1.6)

chore(TDQ-13914): bump version to 1.7.0-SNAPSHOT on master

---

dataquality-semantic/src/main/resources/index/INDEX_NAMES.md

* chore(TDQ-13811): add origin of semantic types data
* chore(TDQ-13811): review commit
* chore(TDQ-13811): add new semantic types
* chore(TDQ-13811): modify semantic type order
* chore(TDQ-13811): HR_DEPARTMENT add
* chore(TDQ-13811): hr_department_cleaned.csv
* chore(TDQ-13811):TDQ to Talend

chore(TDQ-13811): add origin of semantic types data (#140)

---

dataquality-survivorship/src/main/java/org/talend/survivorship/model/DataSet.java
dataquality-survivorship/src/test/java/org/talend/survivorship/SurvivorshipManagerTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/sample/SampleDataConflictMutilGroupFillEmptyBy.java
dataquality-survivorship/src/test/resources/generated/metadata/survivorship/org.talend.survivorship.conflict.fill_empty_by_notIgnoreBlank/SurvivorFlow_0.1.bpmn
dataquality-survivorship/src/test/resources/generated/metadata/survivorship/org.talend.survivorship.conflict.fill_empty_by_notIgnoreBlank/drools_0.1.package
dataquality-survivorship/src/test/resources/generated/metadata/survivorship/org.talend.survivorship.conflict.fill_empty_by_notIgnoreBlank/get FirstName_0.1.drl
dataquality-survivorship/src/test/resources/org.talend.survivorship.conflict/mutilGroupConflicts.csv

not use "fill empty by" and added junit for it

bug fixed TDQ-13981 when tRuleSurvivorship input data has two groups can

---

dataquality-survivorship/src/main/java/org/talend/survivorship/action/handler/CRCRHandler.java
dataquality-survivorship/src/main/java/org/talend/survivorship/model/DataSet.java
dataquality-survivorship/src/main/java/org/talend/survivorship/model/SurvivedResult.java
dataquality-survivorship/src/test/java/org/talend/survivorship/SurvivorshipManagerTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/sample/SampleDataConflictMutilGroupFillEmptyBy.java

when rules doesn't resolve the conflict

bug fixed TDQ-13983 "Conflict" column doesn't show conflict columnName

---

dataquality-survivorship/src/main/java/org/talend/survivorship/action/SurviveAsAction.java
dataquality-survivorship/src/test/java/org/talend/survivorship/action/SurviveAsActionTest.java

bug fixed TDQ-13994 fixed null pointer exception for tRulesurvivorship

---

dataquality-survivorship/src/main/java/org/talend/survivorship/model/DataSet.java
dataquality-survivorship/src/test/java/org/talend/survivorship/SurvivorshipManagerTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/sample/SampleDataConflictMutilGroupConflictDisError.java
dataquality-survivorship/src/test/resources/generated/metadata/survivorship/org.talend.survivorship.conflict.conflict_display_error/SurvivorFlow_0.1.bpmn
dataquality-survivorship/src/test/resources/generated/metadata/survivorship/org.talend.survivorship.conflict.conflict_display_error/drools_0.1.package
dataquality-survivorship/src/test/resources/generated/metadata/survivorship/org.talend.survivorship.conflict.conflict_display_error/getFirstName_0.1.drl
dataquality-survivorship/src/test/resources/generated/metadata/survivorship/org.talend.survivorship.conflict.conflict_display_error/getLastName_0.1.drl

certain rules combine, the Conflict value show on a wrong row

bug fixed TDQ-13984 tRuleSurvivorship-Remove Duplicate can not run at

---

dataquality-libraries/pom.xml
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/type/TypeInferenceUtils.java
dataquality-statistics/src/test/java/org/talend/dataquality/statistics/numeric/summary/MinMaxValueAnalyzerTest.java
dataquality-statistics/src/test/java/org/talend/dataquality/statistics/type/TypeInferenceUtilsTest.java

The daikon PR https://github.com/Talend/daikon/pull/261 is required

feat(TDQ-13103): update pattern to valid percentages

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

Update release version to 1.7.1-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 1.7.1-SNAPSHOT

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java

Update dq lib version to 1.7.1, please help review it!

Update dq lib version to 1.7.1 for component

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 1.6.5-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 1.6.5-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 1.7.2-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 1.7.2-SNAPSHOT

---

dataquality-record-linkage/src/main/java/org/talend/dataquality/matchmerge/Attribute.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/matchmerge/AttributeValues.java

"Attribute" and "AttributeValues" .

TDQ-14333 in order to work for "store on disk",Serializable classes

---

dataquality-converters/src/main/java/org/talend/dataquality/converters/DateCalendarConverter.java
dataquality-converters/src/test/java/org/talend/dataquality/converters/DateCalendarConverterTest.java

TDQ-14421 use smart resolve mode for JapaneseChronology to avoid unit

---

dataquality-semantic/src/main/java/org/talend/dataquality/semantic/api/CategoryRegistryManager.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/index/LuceneIndex.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/recognizer/CategoryRecognizerBuilder.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/api/CategoryRegistryManagerTest.java

share dict;revert last commit "public" to "private".

TDQ-14111 Create a new method to find similar value from customer or

---

dataquality-semantic/src/main/java/org/talend/dataquality/semantic/recognizer/DefaultCategoryRecognizer.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/statistics/SemanticAnalyzerTest.java

fingerPrint, tokenized with Any order, max Levenshtein distance=2

feat(TDQ-14062): fuzzy matching on semantic type name

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 1.6.6-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 1.6.6-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 4.0.3-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 4.0.3-SNAPSHOT

---

dataquality-record-linkage/changelog.txt
dataquality-record-linkage/src/main/java/org/talend/dataquality/matchmerge/mfb/MFBRecordMerger.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/genkey/BlockingKeyHandler.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/AbstractRecordGrouping.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/AnalysisMatchRecordGrouping.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/TSwooshGrouping.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/swoosh/DQMFBRecordMerger.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/record/linkage/grouping/SwooshRecordGroupingTest.java
dataquality-record-linkage/src/test/resources/org/talend/dataquality/record/linkage/grouping/incoming_customers_swoosh2.txt

and tMatchGroup
- add method and parameter to support it
- add junit

feat TDQ-14276 support "most recent" and "most ancient" in matchAnalysis

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 4.0.4-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 4.0.4-SNAPSHOT

---

dataquality-semantic/src/main/java/org/talend/dataquality/semantic/api/internal/CustomDocumentIndexAccess.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/api/internal/CustomMetadataIndexAccess.java

* TDQ-14733 : refresh the searcherManager
* TDQ-14733 : refresh the searcherManager for documents too

TDQ-14733 : refresh the searcherManager (#304)

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 5.0.1-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 5.0.1-SNAPSHOT

---

dataquality-semantic/src/main/java/org/talend/dataquality/semantic/api/CustomDictionaryHolder.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/CategoryRegistryManagerAbstract.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/classifier/impl/DataDictFieldClassifierTest.java

* bug(TDQ-14914): fix the deletion of Talend semantic type
* bug(TDQ-14914): review commit
* bug(TDQ-14914): review commit

bug(TDQ-14914): fix the deletion of Talend semantic type (#320)

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 5.0.2-SNAPSHOT, please help review it!

chore(TDQ-15060/TDQ-14912): bump to next dev version 5.0.2-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 5.0.3-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 5.0.3-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 5.1.0-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 5.1.0-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 6.0.0-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 6.0.0-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): bump to next dev version 5.0.4-SNAPSHOT, please help review it!

chore(Jenkins): bump to next dev version 5.0.4-SNAPSHOT

---

dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/Function.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/GenerateFromFile.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/GenerateFromFileHash.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/MaskAddress.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/semantic/GenerateFromFileStringProvided.java
dataquality-sampling/src/test/java/org/talend/dataquality/datamasking/functions/FunctionTest.java
dataquality-sampling/src/test/java/org/talend/dataquality/datamasking/semantic/GenerateFromFileStringProvidedTest.java

item from file" when set a non exist file path

bugfix(TDQ-14996): Datamasking not work with the function "Replace by

---

dataquality-sampling/src/test/java/org/talend/dataquality/datamasking/functions/GenerateUniquePhoneNumberUsTest.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/datamasking/SemanticMaskerFunctionFactory.java

fix(TDQ-14227): Add setRandom method to avoid mask action make invalid

---

dataquality-semantic/src/main/java/org/talend/dataquality/semantic/sampling/SemanticCategory.java

bugfix(TDQ-15357): implements cloneable interface because support clone

---

dataquality-text-japanese/src/main/java/org/talend/dataquality/jp/tokenization/TextTokenizer.java
dataquality-text-japanese/src/main/java/org/talend/dataquality/jp/tokenization/TextTokenizerBase.java
dataquality-text-japanese/src/main/java/org/talend/dataquality/jp/transliteration/TextTransliterator.java
dataquality-text-japanese/src/test/java/org/talend/dataquality/jp/tokenization/TextTokenizerTest.java

… tokenizer should inside constructor

feat(TDQ-15285): correct initialization-on-demand holder

---

dataquality-survivorship/src/main/java/org/talend/survivorship/SurvivorshipManager.java

each job. just use ClassPath to get them.

fix(TDQ-15215):After TUP-16660, The survivorship rules are exported for

---

dataquality-record-linkage/src/test/java/org/talend/windowkey/AlgoBoxTest.java

feat(TDQ-15237) : add testcases about tGenKey support Japanese

---

dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/Function.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/MaskAddress.java
dataquality-sampling/src/test/java/org/talend/dataquality/datamasking/functions/FunctionTest.java
dataquality-sampling/src/test/java/org/talend/dataquality/datamasking/functions/MaskAddressTest.java

feat(TDQ-15608): support more keywords for address masking function

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): Bump to next dev version 6.1.1-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 6.1.1-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): Bump to next dev version 6.1.2-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 6.1.2-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): Bump to next dev version 6.2.0-SNAPSHOT, please help review it!

chore(TDQ-15942): Bump to next dev version 6.2.0-SNAPSHOT

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/pom.xml

chore(Jenkins): Bump to next dev version 6.2.0-SNAPSHOT, please help review it!

chore(Jenkins): Update daikon version to 0.29.0-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): Bump to next dev version 6.1.6-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 6.1.6-SNAPSHOT

---

dataquality-survivorship/src/main/java/org/talend/survivorship/action/handler/CRCRHandler.java
dataquality-survivorship/src/main/java/org/talend/survivorship/action/handler/HandlerParameter.java
dataquality-survivorship/src/main/java/org/talend/survivorship/model/DataSet.java
dataquality-survivorship/src/main/java/org/talend/survivorship/model/SubDataSet.java
dataquality-survivorship/src/test/java/org/talend/survivorship/SurvivorshipManagerTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/action/handler/CRCRHandlerTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/action/handler/HandlerParameterTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/model/DataSetTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/model/SubDataSetTest.java

chore(TDQ-15920): tRulesurvivorship after the CR table, make the

---

dataquality-survivorship/src/main/java/org/talend/survivorship/action/handler/CRCRHandler.java
dataquality-survivorship/src/main/java/org/talend/survivorship/action/handler/HandlerParameter.java
dataquality-survivorship/src/main/java/org/talend/survivorship/model/DataSet.java
dataquality-survivorship/src/main/java/org/talend/survivorship/model/SubDataSet.java
dataquality-survivorship/src/test/java/org/talend/survivorship/SurvivorshipManagerTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/action/handler/CRCRHandlerTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/action/handler/HandlerParameterTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/model/DataSetTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/model/SubDataSetTest.java

* chore(TDQ-15920): tRulesurvivorship after the CR table, make the
Conflict mark is correct
* chore(TDQ-15920): imporve code as codacy request
* chore(TDQ-15920): improve code again
* fix(TDQ-15920): improve about survivorAs function make it show conlict
mark correctly

chore(TDQ-15920): tRulesurvivorship after the CR table, make the (#505)

---

dataquality-text-japanese/src/main/java/org/talend/dataquality/jp/numbers/JapaneseNumberNormalizer.java
dataquality-text-japanese/src/test/java/org/talend/dataquality/jp/numbers/JapaneseNumberNormalizerTest.java

Feat TDQ-15959 tJapaneseNumberNormalize needs to handle percentage

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-semantic-model/META-INF/MANIFEST.MF
dataquality-semantic-model/pom.xml
dataquality-semantic/META-INF/MANIFEST.MF
dataquality-semantic/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml

chore(Jenkins): Bump to next dev version 6.1.7-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 6.1.7-SNAPSHOT

---

dataquality-converters/src/test/java/org/talend/dataquality/converters/character/CharWidthConverterTest.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/pom.xml

chore(Jenkins): Bump to next dev version 6.2.0-SNAPSHOT, please help review it!

chore(TDQ-16333): update daikon version to 0.31.1

---

dataquality-semantic-model/src/main/java/org/talend/dataquality/semantic/model/DQAction.java
dataquality-semantic-model/src/main/java/org/talend/dataquality/semantic/model/DQCategory.java
dataquality-semantic-model/src/main/java/org/talend/dataquality/semantic/model/DQCategoryAction.java
dataquality-semantic-model/src/main/java/org/talend/dataquality/semantic/model/DQDocument.java
dataquality-semantic-model/src/main/java/org/talend/dataquality/semantic/model/DQDocumentAction.java
dataquality-semantic-model/src/main/java/org/talend/dataquality/semantic/model/DQFilter.java
dataquality-semantic-model/src/main/java/org/talend/dataquality/semantic/model/DQProvisioningAction.java
dataquality-semantic-model/src/main/java/org/talend/dataquality/semantic/model/DQRegEx.java
dataquality-semantic-model/src/main/java/org/talend/dataquality/semantic/model/DQValidator.java

Add action and builder for TSD-220 updates.

feat(TSD-220): add action and builders

---

.gitignore
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/extraction/ExtractFromDictionary.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/extraction/MatchedPart.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/extraction/MatchedPartDict.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/extraction/MatchedPartRegex.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/extraction/TokenizedString.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/extraction/ExtractFromDictionaryTest.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/extraction/FieldExtractionFunctionTest.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/extraction/MatchedPartTest.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/extraction/TokenizedStringTest.java

* Fix(TDQ-16650) Fix missing separators in matches from dictionaries
* Add tests and clean code
* Fix(TDQ-16650) Clean code

Fix(TDQ-16650) Fix Missing Separators for certain matches (#584)

---

dataquality-semantic/src/main/java/org/talend/dataquality/semantic/datamasking/GenerateFromCompound.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/datamasking/GenerateFromCompoundTest.java

* bugfix(TDQ-16673): set repeatable Random in method processDistribution
* add unit test

bugfix(TDQ-16673): Consistent repeatable SemanticType masking (#594)

---

dataquality-semantic/src/main/java/org/talend/dataquality/semantic/extraction/ExtractFromDictionary.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/extraction/FieldExtractionFunction.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/extraction/MatchedPartDict.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/extraction/TokenizedString.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/extraction/ExtractFromDictionaryTest.java
dataquality-semantic/src/test/java/org/talend/dataquality/semantic/extraction/FieldExtractionFunctionTest.java

* Fix(TDQ-16650) Fix missing separators in matches from dictionaries
* Add tests and clean code
* Fix(TDQ-16650) Clean code
* bug(TDQ-16651) - extract part of dict with single quote
* formatting
* add exception catching

fix(TDQ-16650): issue with apostrophe with extraction by DICO (#593)

---

dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/DateVariance.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/Function.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/GenerateBetweenDate.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/functions/KeepYear.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/semantic/AbstractDateFunction.java
dataquality-sampling/src/main/java/org/talend/dataquality/datamasking/semantic/DateFunctionAdapter.java
dataquality-sampling/src/test/java/org/talend/dataquality/datamasking/semantic/DateFunctionAdapterTest.java
dataquality-semantic/src/main/java/org/talend/dataquality/semantic/datamasking/SemanticMaskerFunctionFactory.java

* fix(TDQ-16656): consistent masking for dates on different machines
* unit test

fix(TDQ-16656): consistent masking for dates on different machines 

---

dataquality-survivorship/src/main/java/org/talend/survivorship/utils/ChainNodeMap.java
dataquality-survivorship/src/test/java/org/talend/survivorship/utils/ChainNodeMapTest.java

fix(TDQ-16521): fix the issue which disable some rule cause others can

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.0.1-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.0.1-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.0.2-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.0.2-SNAPSHOT

---

dataquality-record-linkage/src/test/java/org/talend/dataquality/record/linkage/attribute/AbstractAttributeMatcherTest.java

Check matching algorithms behavior with non-latin characters

chore(TDQ-6893): add test for

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.1.1-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.1.1-SNAPSHOT

---

dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/utils/SurvivorShipAlgorithmEnum.java

fix(TDQ-17061): Make sure Most trusted source valid for all the data

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.1.2-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.1.2-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.2.0-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.2.0-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.2.1-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.2.1-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.2.2-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.2.2-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.3.0-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.3.0-SNAPSHOT

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.4.0-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.4.0-SNAPSHOT

---

dataquality-libraries/pom.xml

https://jira.talendforge.org/browse/TUP-24026
https://jira.talendforge.org/browse/TDQ-17640

fix(TUP-24026): update jackson to 2.10.0

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.4.1-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.4.1-SNAPSHOT

---

.github/PULL_REQUEST_TEMPLATE.md

- https://jira.talendforge.org/browse/TDQ-17710
update PR template

chore(TDQ-17710): update PR template

---

dataquality-converters/src/test/java/org/talend/dataquality/converters/DateCalendarConverterTest.java
dataquality-converters/src/test/java/org/talend/dataquality/converters/JulianDayConverterTest.java

* feat(TDQ-15809) New Japanese calendar

feat(TDQ-15809) New Japanese calendar (#658)

---

dataquality-record-linkage/CHANGELOG.md
dataquality-record-linkage/src/main/java/org/talend/dataquality/matchmerge/mfb/MatchResult.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/matchmerge/mfb/MatchResultTest.java

fix(TDQ-17709): fix precision issues to ensure that two records match if the score is greater than or equal to the threshold

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java

chore(TDQ-17923): fix build due to format issue

---

dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/utils/StringComparisonUtil.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/record/linkage/utils/StringComparisonUtilTest.java

fix(TDQ-17851) support SurrogatePair and improve performance

---

dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/utils/StringComparisonUtil.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/record/linkage/utils/StringComparisonUtilTest.java

fix(TDQ-17851)support SurrogatePair and improve performance

---

ci/Jenkinsfile
dataquality-common/src/test/java/org/talend/dataquality/common/pattern/TextPatternUtilTest.java

- https://jira.talendforge.org/browse/TDQ-17834
CI Migration from Jenkins 1 to Jenkins 2
Add JekinsFile to work with Jenkins 2

Chore(TDQ-17834): Add JenkinsFile for CI with Jenkins 2

---

ci/vulnerability-check/Jenkinsfile
ci/vulnerability-check/vulnerabilities-report.js

- https://jira.talendforge.org/browse/TDQ-17842
automate vulnerability analysis on Jenkins jobs.

feat(TDQ-17847) : automate veracode on Jenkins

---

ci/vulnerability-check/Jenkinsfile

- https://jira.talendforge.org/browse/TDQ-17847

improve veracode jenkins file

---

ci/vulnerability-check/Jenkinsfile

- https://jira.talendforge.org/browse/TDQ-17847

fix TSBI version

---

ci/release/Jenkinsfile

- https://jira.talendforge.org/browse/TDQ-17834

Chore(TDQ-17834) Add Jenkinsfile for Release

---

ci/Jenkinsfile
ci/release/Jenkinsfile
ci/vulnerability-check/Jenkinsfile

* Chore(TDQ-17834): Add JenkinsFile for CI with Jenkins 2 (#757)
- https://jira.talendforge.org/browse/TDQ-18027

Chore(TDQ-18027) Backport Jenkinsfiles (#771)

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java

* Fix(TDQ-18064) : Don't update daikon version when empty
* Fix format

Fix(TDQ-18064) : Don't update daikon version when empty (#778)

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 8.1.0-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 8.1.0-SNAPSHOT

---

dataquality-sampling/CHANGELOG.md
dataquality-sampling/src/test/java/org/talend/dataquality/duplicating/FieldModifierTest.java

- https://jira.talendforge.org/browse/TDQ-18085

Chore(TDQ-18085): Fix unstable date test using today's date

---

dataquality-statistics/src/test/java/org/talend/dataquality/statistics/semantic/ConcurrentAnalyzerTest.java

- https://jira.talendforge.org/browse/TDQ-18024

chore(TDQ-18024): ignore an unstable test

---

dataquality-standardization/CHANGELOG.md
dataquality-standardization/src/main/java/org/talend/dataquality/standardization/index/SynonymIndexBuilder.java
dataquality-standardization/src/main/resources/messages.properties

fix(TDQ-18091) more clear error message.

---

ci/Jenkinsfile

Ql/tdq 18203/jenkins sonar qube

---

ci/Jenkinsfile
ci/release/Jenkinsfile

- https://jira.talendforge.org/browse/TDQ-18088
- mci not performed with -U option in build job
- Useless clean during deploy phase
- Useless paramter in release job

Workitem(TDQ-18088) Jenkins CI Improvements

---

dataquality-libraries/pom.xml

- https://jira.talendforge.org/browse/TDQ-18146
upgrade Jacoco plugin

chore(TDQ-18146) : upgrade jacoco configuration

---

dataquality-libraries/pom.xml

- https://jira.talendforge.org/browse/TDQ-18146

delete unused properties

---

ci/Jenkinsfile

fix(TDQ-18203) change the url and project id/name

---

dataquality-common/pom.xml
dataquality-converters/pom.xml
dataquality-email/pom.xml
dataquality-libraries/pom.xml
dataquality-phone/pom.xml
dataquality-record-linkage/pom.xml
dataquality-sampling/pom.xml
dataquality-standardization/pom.xml
dataquality-survivorship/pom.xml
dataquality-text-japanese/pom.xml
dataquality-wordnet/pom.xml

- https://jira.talendforge.org/browse/TDQ-18383

fix(TDQ-18383) Upgrade log4j to 2.X

---

dataquality-standardization/src/main/java/org/talend/dataquality/standardization/index/SynonymIndexBuilder.java
dataquality-standardization/src/main/resources/messages.properties

Chore(TDQ-18091) Add a new message key

---

CHANGELOG.md
dataquality-common/CHANGELOG.md
dataquality-converters/CHANGELOG.md
dataquality-email/CHANGELOG.md
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-phone/CHANGELOG.md
dataquality-record-linkage/CHANGELOG.md
dataquality-sampling/CHANGELOG.md
dataquality-standardization/CHANGELOG.md
dataquality-statistics/CHANGELOG.md
dataquality-survivorship/CHANGELOG.md
dataquality-text-japanese/CHANGELOG.md
dataquality-wordnet/CHANGELOG.md

chore(TDQ-17788): add nice href for changelogs

---

ci/Jenkinsfile
ci/release/Jenkinsfile
dataquality-libraries/pom.xml

- https://jira.talendforge.org/browse/TDQ-18431

chore(TDQ-18431) Backport CI Changes

---

dataquality-common/CHANGELOG.md
dataquality-common/pom.xml
dataquality-converters/pom.xml
dataquality-email/pom.xml
dataquality-libraries/pom.xml
dataquality-phone/CHANGELOG.md
dataquality-phone/pom.xml
dataquality-record-linkage/CHANGELOG.md
dataquality-record-linkage/pom.xml
dataquality-sampling/CHANGELOG.md
dataquality-sampling/pom.xml
dataquality-standardization/CHANGELOG.md
dataquality-standardization/pom.xml
dataquality-survivorship/CHANGELOG.md
dataquality-survivorship/pom.xml
dataquality-text-japanese/CHANGELOG.md
dataquality-text-japanese/pom.xml
dataquality-wordnet/CHANGELOG.md
dataquality-wordnet/pom.xml

- https://jira.talendforge.org/browse/TDQ-18383

fix(TDQ-18383) Upgrade log4j to 2.X (#798)

---

CHANGELOG.md
dataquality-common/CHANGELOG.md
dataquality-converters/CHANGELOG.md
dataquality-email/CHANGELOG.md
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-phone/CHANGELOG.md
dataquality-record-linkage/CHANGELOG.md
dataquality-sampling/CHANGELOG.md
dataquality-standardization/CHANGELOG.md
dataquality-statistics/CHANGELOG.md
dataquality-survivorship/CHANGELOG.md
dataquality-text-japanese/CHANGELOG.md
dataquality-wordnet/CHANGELOG.md

* chore(TDQ-17788): add nice href for changelogs
- https://jira.talendforge.org/browse/TDQ-17788

chore(TDQ-17788): add nice href for changelogs (#775)

---

ci/Jenkinsfile

- https://jira.talendforge.org/browse/TDQ-18381

Chore(TDQ-18381): Fix Sonar project key name

---

ci/Jenkinsfile

- https://jira.talendforge.org/browse/TDQ-18381

Fix typo in JenkinsFile

---

ci/Jenkinsfile

- https://jira.talendforge.org/browse/TDQ-18381

Chore(TDQ-18381): [CI] Add Variable for Sonar base URL

---

.github/workflows/rebase.yml

- https://jira.talendforge.org/browse/TDQ-18521

workitem(TDQ-18521): Add reminder to update changelog

---

dataquality-record-linkage/CHANGELOG.md

TDQ-18347 fix changelog

---

dataquality-record-linkage/src/test/resources/log4j.xml
dataquality-sampling/src/main/java/org/talend/dataquality/sampling/license.txt
pom.xml

- https://jira.talendforge.org/browse/TDQ-17091

Chore(TDQ-17091): Switch to using https wherever possible

---

dataquality-standardization/CHANGELOG.md

Fix changelog

---

dataquality-survivorship/src/main/java/org/talend/survivorship/action/handler/HandlerParameter.java
dataquality-survivorship/src/main/java/org/talend/survivorship/model/DataSet.java
dataquality-survivorship/src/test/java/org/talend/survivorship/action/handler/HandlerParameterTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/model/DataSetTest.java

checked get IndexOutOfBoundsException

fix(TDQ-16966 TDQ-18556): fixed tRuleSurvivorship job with "Define conflict rule"

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(TPS-4183) release a new dq-lib-se 7.0.2

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java

fix(TDQ-18556): Improve CI and avoid ClassNotfound

---

dataquality-common/src/main/java/org/talend/dataquality/common/inference/AvroQualityAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/type/AvroDataTypeAnalyzer.java
dataquality-statistics/src/test/java/org/talend/dataquality/statistics/quality/AvroDataTypeQualityAnalyzerTest.java
dataquality-statistics/src/test/java/org/talend/dataquality/statistics/type/AvroDataTypeAnalyzerTest.java

chore(TDQ-18422): add support for maps and arrays leaves

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.0.3-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.0.3-SNAPSHOT

---

dataquality-survivorship/changelog.txt
dataquality-survivorship/src/main/java/org/talend/survivorship/model/DataSet.java
dataquality-survivorship/src/main/java/org/talend/survivorship/utils/ChainNodeMap.java

Ql/fix/tdq 18567/t rule survivorship index out of bounds ex 7.0

---

dataquality-survivorship/src/test/java/org/talend/survivorship/model/DataSetTest.java

fix(TDQ-18567): Add a junit test

---

dataquality-common/META-INF/MANIFEST.MF
dataquality-common/pom.xml
dataquality-converters/META-INF/MANIFEST.MF
dataquality-converters/pom.xml
dataquality-email/META-INF/MANIFEST.MF
dataquality-email/pom.xml
dataquality-libraries-devops/META-INF/MANIFEST.MF
dataquality-libraries-devops/pom.xml
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries/META-INF/MANIFEST.MF
dataquality-libraries/pom.xml
dataquality-phone/META-INF/MANIFEST.MF
dataquality-phone/pom.xml
dataquality-record-linkage/META-INF/MANIFEST.MF
dataquality-record-linkage/pom.xml
dataquality-sampling/META-INF/MANIFEST.MF
dataquality-sampling/pom.xml
dataquality-standardization/META-INF/MANIFEST.MF
dataquality-standardization/pom.xml
dataquality-statistics/META-INF/MANIFEST.MF
dataquality-statistics/pom.xml
dataquality-survivorship/META-INF/MANIFEST.MF
dataquality-survivorship/pom.xml
dataquality-text-japanese/META-INF/MANIFEST.MF
dataquality-text-japanese/pom.xml
dataquality-wordnet/META-INF/MANIFEST.MF
dataquality-wordnet/pom.xml
pom.xml

chore(Jenkins): Bump to next dev version 7.0.4-SNAPSHOT, please help review it!

chore(Jenkins): Bump to next dev version 7.0.4-SNAPSHOT

---

dataquality-survivorship/CHANGELOG.md
dataquality-survivorship/src/main/java/org/talend/survivorship/model/DataSet.java
dataquality-survivorship/src/main/java/org/talend/survivorship/utils/ChainNodeMap.java
dataquality-survivorship/src/test/java/org/talend/survivorship/SurvivorshipManagerTest.java
dataquality-survivorship/src/test/java/org/talend/survivorship/model/DataSetTest.java
dataquality-survivorship/src/test/resources/org.talend.survivorship.conflict/conflictsFirstGroup.csv

fix(TDQ-18567) also clear 'orderMap' in ChainNodeMap for a new dataset

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponent4libphonenumber.java
dataquality-phone/CHANGELOG.md
dataquality-phone/pom.xml

chore(TDQ-18429): Upgrade versions of google phone library to newest (#816)

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponent4libphonenumber.java
dataquality-phone/CHANGELOG.md
dataquality-phone/pom.xml

Reverts Talend/data-quality#849

Revert "chore(TDQ-18429): Upgrade versions of google phone library to newest (#816)"

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponentDefinition.java
dataquality-libraries/pom.xml

fix(TDQ-18464) Upgrade crypto-utils to 1.15.0

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdateComponent4libphonenumber.java
dataquality-phone/CHANGELOG.md
dataquality-phone/pom.xml

- https://jira.talendforge.org/browse/TDQ-18558
upgrade the jar from 8.10.5 to 8.12.3
upgrade the jar from 8.10.5 to 8.12.3

chor(TDQ-18429): Upgrade versions of google phone library to newest 

---

ci/vulnerability-check/JenkinsfileVeracodeScan

fix(TDQ-18663) Add a trigger

---

ci/vulnerability-check/JenkinsfileVeracodeScan

fix(TDQ-18663) Test the cron on master

---

ci/vulnerability-check/JenkinsfileVeracodeScan

fix(TDQ-18663) Change back the trigger to Sunday

---

dataquality-record-linkage/CHANGELOG.md
dataquality-record-linkage/src/main/java/org/talend/dataquality/matchmerge/mfb/MFBRecordMatcher.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/AbstractRecordGrouping.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/record/CombinedRecordMatcher.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/matchmerge/mfb/MFBOrderTest.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/record/linkage/grouping/SwooshRecordGroupingTest.java

fix(TDQ-18542) multi match rule

---

dataquality-record-linkage/CHANGELOG.md
dataquality-record-linkage/src/main/java/org/talend/dataquality/matchmerge/mfb/MFBRecordMatcher.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/grouping/AbstractRecordGrouping.java
dataquality-record-linkage/src/main/java/org/talend/dataquality/record/linkage/record/CombinedRecordMatcher.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/matchmerge/mfb/MFBOrderTest.java
dataquality-record-linkage/src/test/java/org/talend/dataquality/record/linkage/grouping/SwooshRecordGroupingTest.java

fix(TDQ-18542) multi match rule (#864)

---

ci/vulnerability-check/JenkinsfileVeracodeScan

chore: Change Veracode app & sandbox name for static scan

---

dataquality-common/CHANGELOG.md
dataquality-libraries/pom.xml
dataquality-statistics/CHANGELOG.md

- https://jira.talendforge.org/browse/TDQ-17694

chore(TDQ-17694): upgrade daikon to 1.16.2 to fix Jackson Data Mapper Issues

---

dataquality-libraries/pom.xml

fix(TDQ-18385) Apache Common Codec issues

---

dataquality-statistics/src/test/java/org/talend/dataquality/statistics/semantic/ConcurrentAnalyzerTest.java

Backport chore(TDQ-18024): ignore an unstable test (#786)

---

dataquality-common/CHANGELOG.md
dataquality-libraries/pom.xml
dataquality-record-linkage/CHANGELOG.md
dataquality-sampling/CHANGELOG.md
dataquality-statistics/CHANGELOG.md
dataquality-survivorship/CHANGELOG.md

fix(TDQ-18385) using codec 1.14

---

dataquality-libraries/pom.xml

This reverts commit d85cc7f1aaa281770c8ddc954002df389ce0c00a.

Revert "fix(TDQ-18385) Apache Common Codec issues (#874)"

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/ReleaseVersionBumper.java
dataquality-libraries/pom.xml

chore(TDQ-18948) update the daikon version to 1.16.3

---

dataquality-common/CHANGELOG.md
dataquality-libraries/pom.xml
dataquality-statistics/CHANGELOG.md

- https://jira.talendforge.org/browse/TDQ-19066
fix Security issue about jackson-databind issues
upgrade jackson-databind from 2.10.2 to 2.11.3

fix(TDQ-19066): Fix jackson-databind issues

---

dataquality-common/CHANGELOG.md
dataquality-libraries/pom.xml
dataquality-statistics/CHANGELOG.md

- https://jira.talendforge.org/browse/TDQ-19066
Security issue about jackson-databind.jar
upgrade the version to 2.11.3

Zshen/bugfix/tdq 19066 upgrade jackson databind to 2.11.3

---

ci/release/Jenkinsfile

chore(TDQ-19019) add a new parameter daikon_version

---

dataquality-common/CHANGELOG.md
dataquality-libraries/pom.xml
dataquality-statistics/CHANGELOG.md

- https://jira.talendforge.org/browse/TDQ-19045

fix(TDQ-19045) Update Jackson Databind to 2.11.4

---

README.md
dataquality-common/CHANGELOG.md
dataquality-common/src/main/java/org/talend/dataquality/common/util/AvroUtils.java
dataquality-common/src/test/java/org/talend/dataquality/common/util/AvroUtilsTest.java
dataquality-common/src/test/resources/org/talend/dataquality/common/util/UnionOfComplexRefType_dereferencedSchema.avsc
dataquality-common/src/test/resources/org/talend/dataquality/common/util/complexWithProp.avsc
dataquality-common/src/test/resources/org/talend/dataquality/common/util/complexWithPropExpected.avsc
dataquality-common/src/test/resources/org/talend/dataquality/common/util/is_identity.avsc
dataquality-common/src/test/resources/org/talend/dataquality/common/util/unionStringWithProp.avsc
dataquality-common/src/test/resources/org/talend/dataquality/common/util/unionStringWithPropExpected.avsc

- https://jira.talendforge.org/browse/TPRUN-514

chore(TPRUN-514): Refactor AvroUtils for TPRUN-14

---

README.md

https://jira.talendforge.org/browse/TUP-30114

feat(TUP-30114) update copyright.

---

dataquality-statistics/CHANGELOG.md
dataquality-statistics/pom.xml

- https://jira.talendforge.org/browse/TDQ-19292

Chore(TDQ-19292): Fix jackson mapper issue

---

dataquality-survivorship/CHANGELOG.md
dataquality-survivorship/pom.xml
dataquality-survivorship/src/main/java/org/talend/survivorship/action/ExpressionAction.java
dataquality-survivorship/src/main/java/org/talend/survivorship/action/MatchRegexAction.java

Fix     TDQ-19243 [TB:3d] [Security] Fix CWE-95 in ExpressionAction

---

dataquality-statistics/CHANGELOG.md
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/type/AvroDataTypeDiscoveryAnalyzer.java

- https://jira.talendforge.org/browse/TPRUN-354

workitem(TPRUN-354): Improve native discovery for typed data

---

dataquality-libraries-devops/src/main/java/org/talend/dataquality/libraries/devops/UpdatePluginsVersionInComponents.java

chore(TDQ-19245) update the component plugin version

---

dataquality-statistics/CHANGELOG.md
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/datetime/SystemDateTimePatternManager.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/type/SortedList.java
dataquality-statistics/src/test/java/org/talend/dataquality/statistics/type/SortedListTest.java

- https://jira.talendforge.org/browse/TPRUN-953

chore(TPRUN-953): Refactor SortedList

---

dataquality-common/CHANGELOG.md
dataquality-common/src/main/java/org/talend/dataquality/common/util/AvroUtils.java
dataquality-common/src/test/java/org/talend/dataquality/common/util/AvroUtilsTest.java
dataquality-statistics/src/test/java/org/talend/dataquality/statistics/type/AvroDataTypeDiscoveryAnalyzerTest.java

- https://jira.talendforge.org/browse/TPRUN-979

chore(TPRUN-979): Refactor AvroUtils for Validation processor

---

dataquality-common/CHANGELOG.md
dataquality-common/src/main/java/org/talend/dataquality/common/inference/Analyzers.java
dataquality-common/src/main/java/org/talend/dataquality/common/inference/ResizableList.java
dataquality-common/src/test/java/org/talend/dataquality/common/inference/ResizableListTest.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/cardinality/CardinalityAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/cardinality/CardinalityHLLAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/frequency/AbstractFrequencyAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/frequency/DataTypeFrequencyAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/frequency/pattern/CompositePatternFrequencyAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/numeric/histogram/HistogramAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/numeric/quantile/QuantileAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/numeric/quantile/TDigestAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/numeric/summary/SummaryAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/quality/DataTypeQualityAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/text/TextLengthAnalyzer.java
dataquality-statistics/src/main/java/org/talend/dataquality/statistics/type/DataTypeAnalyzer.java

- https://jira.talendforge.org/browse/TPRUN-952
In `data-quality-ee`, ResizableList has been used in two places:
```
org/talend/dataquality/semantic/statistics/SemanticQualityAnalyzer.java:33:    
private final ResizableList<ValueQualityStatistics> results = new ResizableList<>(ValueQualityStatistics.class);
org/talend/dataquality/semantic/statistics/SemanticAnalyzer.java:43:    
private final ResizableList<SemanticType> results = new ResizableList<>(SemanticType.class);
```
should be rewritten …

chore(TPRUN-952): Refactor ResizableList

---

dataquality-survivorship/CHANGELOG.md
dataquality-survivorship/pom.xml

fix(TDQ-19472) Fix XStream Core issues (to 1.4.17)

---

dataquality-common/CHANGELOG.md
dataquality-libraries/pom.xml
dataquality-record-linkage/CHANGELOG.md
dataquality-standardization/CHANGELOG.md
dataquality-statistics/CHANGELOG.md

chore(TDQ-19311) Fix Apache Commons IO issues (to 2.8.0)

---

dataquality-survivorship/CHANGELOG.md
dataquality-survivorship/pom.xml
dataquality-survivorship/src/main/java/org/talend/survivorship/SurvivorshipManager.java
dataquality-survivorship/src/test/java/org/talend/survivorship/SurvivorshipManagerTest.java

fix(TDQ-20485):Upgrade drools to 7.73.0 (#1069)
